version: '3.3'

services:
  dm-bruschatka-frontend-node:
    container_name: dm-bruschatka-frontend-node
    image: node:8
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
      - ../mos-bruschatka-ru:/home/node/mos-bruschatka-ru
    command: "sh -c 'npm install && npm run watch'"
